spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://db:5432/casbin_test
    user: postgres
    password: Caranvalis
    schemas: public
    baseline-on-migrate: true
    fail-on-missing-locations: true
  r2dbc:
    url: r2dbc:postgresql://db:5432/casbin_test?schema=public
    username: postgres
    password: Caranvalis
logging:
  level:
    org.flywaydb: DEBUG
    com.casbin: DEBUG