apiVersion: 1
datasources:
  - name: MyPrometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: loki
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
        - datasourceUid: tempo
          matcherRegex: "traceID=([a-zA-Z0-9]+)"
          name: TraceID
          url: "$${__value.raw}"