spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/casbin_test
    username: postgres
    password: Caranvalis

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG

server:
  port: 8080