server:
  http_listen_port: 4318

distributor:
  receivers:
    otlp:
      protocols:
        http:

ingester:
  trace_idle_period: 10s
  max_block_bytes: 100_000_000
  max_block_duration: 5m

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces